part of 'models.dart';

class EventInfo extends Equatable {
  final int id, idUser;
  final String name,
      cost,
      posterEvent,
      description,
      category,
      location,
      benefits,
      requirements,
      organizer,
      contactOrganizer,
      status; //ditinjau, disetujui, ditolak,
  final Users user;
  final DateTime timeCreate, timeUpdate, timeStart, timeReglimit;
  EventInfo({
    this.id,
    this.user,
    @required this.idUser,
    @required this.name,
    @required this.cost,
    this.posterEvent,
    @required this.description,
    @required this.category,
    @required this.location,
    @required this.benefits,
    @required this.requirements,
    @required this.timeStart,
    @required this.timeReglimit,
    @required this.status,
    @required this.organizer,
    @required this.contactOrganizer,
    this.timeCreate,
    this.timeUpdate,
  });
  @override
  List<Object> get props => [
        id,
        idUser,
        name,
        cost,
        description,
        posterEvent,
        category,
        location,
        benefits,
        requirements,
        user,
        organizer,
        contactOrganizer,
        timeCreate,
        timeUpdate,
        timeStart,
        timeReglimit
      ];

  factory EventInfo.fromJson(Map<String, dynamic> data) {
    return EventInfo(
      id: data['id'],
      idUser: (data['id_user'] is String)
          ? int.parse(data['id_user'])
          : data['id_user'],
      name: data['name'],
      cost: data['cost'],
      posterEvent: data['poster_event'],
      description: data['description'],
      category: data['category'],
      location: data['location'],
      benefits: data['benefits'],
      requirements: data['requirements'],
      status: data['status'],
      organizer: data['organizer'],
      contactOrganizer: data['contact_organizer'],
      timeCreate: DateTime.parse(data['created_at']),
      timeUpdate: DateTime.parse(data['updated_at']),
      timeStart: DateTime.parse(data['time_start']),
      timeReglimit: DateTime.parse(data['time_reglimit']),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      'id_user': idUser,
      'name': name,
      'cost': cost,
      'category': category,
      'description': description,
      'location': location,
      'benefits': benefits,
      'requirements': requirements,
      'status': status,
      'organizer': organizer,
      'contact_organizer': contactOrganizer,
      'time_start': timeStart.toUtc().toString(),
      'time_reglimit': timeReglimit.toUtc().toString()
    };
  }

  EventInfo copyWith({
    int id,
    String name,
    String cost,
    String posterEvent,
    String cotegory,
    String location,
    String benefits,
    String requirements,
    String status,
    String description,
    String organizer,
    String contactOrganizer,
    Users user,
    DateTime timeUpdate,
    DateTime timeStart,
    DateTime timeReglimit,
  }) {
    return EventInfo(
      id: id ?? this.id,
      idUser: this.idUser,
      user: user ?? this.user,
      name: name ?? this.name,
      cost: cost ?? this.cost,
      posterEvent: posterEvent ?? this.posterEvent,
      description: description ?? this.description,
      category: category ?? this.category,
      location: location ?? this.location,
      benefits: benefits ?? this.benefits,
      requirements: requirements ?? this.requirements,
      timeStart: timeStart ?? this.timeStart,
      timeReglimit: timeReglimit ?? this.timeReglimit,
      status: status ?? this.status,
      timeCreate: this.timeCreate,
      timeUpdate: timeUpdate ?? this.timeUpdate,
      contactOrganizer: contactOrganizer ?? this.contactOrganizer,
      organizer: organizer ?? this.organizer,
    );
  }

  EventInfo copyWith2({
    int id,
    String name,
    String cost,
    String posterEvent,
    String cotegory,
    String location,
    String benefits,
    String requirements,
    String status,
    String description,
    String organizer,
    String contactOrganizer,
    Users user,
    DateTime timeUpdate,
    DateTime timeStart,
    DateTime timeReglimit,
  }) {
    return EventInfo(
      id: id ?? this.id,
      idUser: this.idUser,
      user: user ?? this.user,
      name: name ?? this.name,
      cost: cost ?? this.cost,
      description: description ?? this.description,
      category: category ?? this.category,
      location: location ?? this.location,
      benefits: benefits ?? this.benefits,
      requirements: requirements ?? this.requirements,
      timeStart: timeStart ?? this.timeStart,
      timeReglimit: timeReglimit ?? this.timeReglimit,
      status: status ?? this.status,
      timeCreate: this.timeCreate,
      timeUpdate: timeUpdate ?? this.timeUpdate,
      contactOrganizer: contactOrganizer ?? this.contactOrganizer,
      organizer: organizer ?? this.organizer,
    );
  }
}

List<EventInfo> mockEvent = [
  EventInfo(
    id: 1,
    idUser: 1,
    name: 'Seminar Nasional',
    cost: 'Gratiss',
    posterEvent:
        'https://eventkampus.com/data/event/poster/2/seminar-administrasi-bisnis-pnj_1.jpeg',
    description: 'Seminar Inovasi SDM dan Iptek Nuklir',
    category: 'Seminar',
    location: 'Daring',
    benefits: 'E-Sertifikast\nIlmu yang bermanfaat\nrelasi',
    requirements: 'Mahasiswa',
    timeStart: DateTime.utc(
      2021,
      5,
      1,
      8,
    ),
    timeReglimit: DateTime.utc(
      2021,
      4,
      29,
      0,
    ),
    status: 'Publish',
    organizer: 'HIMATIF',
    contactOrganizer: '089713199',
  ),
  EventInfo(
    id: 2,
    idUser: 1,
    name: 'Lomba Poster Malibu',
    cost: 'Gratiss',
    posterEvent:
        'https://kabarkampus.com/wp-content/uploads/2020/11/Lomba-Poster-Malibu.jpg',
    description: 'Seminar Inovasi SDM dan Iptek Nuklir',
    category: 'Lomba',
    location: 'Daring',
    benefits: 'E-Sertifikast\nIlmu yang bermanfaat\nrelasi',
    requirements: 'Mahasiswa',
    timeStart: DateTime.utc(
      2021,
      5,
      1,
      8,
    ),
    timeReglimit: DateTime.utc(
      2021,
      4,
      29,
      0,
    ),
    status: 'Pending',
    organizer: 'HIMATIF',
    contactOrganizer: '089713199',
  ),
  EventInfo(
    id: 3,
    idUser: 1,
    name: 'Seminar Nasional 3',
    cost: 'Gratiss',
    posterEvent:
        'https://eventkampus.com/data/event/poster/2/seminar-nasional-islamic-youngpreneur-in-milenial-era.jpeg',
    description: 'Seminar Inovasi SDM dan Iptek Nuklir',
    category: 'Seminar',
    location: 'Daring',
    benefits: 'E-Sertifikast\nIlmu yang bermanfaat\nrelasi',
    requirements: 'Mahasiswa',
    timeStart: DateTime.utc(
      2021,
      4,
      26,
      8,
    ),
    timeReglimit: DateTime.utc(
      2021,
      4,
      24,
      0,
    ),
    status: 'Publish',
    organizer: 'HIMATIF',
    contactOrganizer: '089713199',
  ),
  EventInfo(
    id: 4,
    idUser: 1,
    name: 'Seminar Nasional 3',
    cost: 'Gratiss',
    posterEvent:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-7zNtR-AC0whgrKIJxr2QUQUZnMamVIXnd87iLiai1becor7iLZZzRWHq3PWxFFj3jOo&usqp=CAU',
    description: 'Seminar Inovasi SDM dan Iptek Nuklir',
    category: 'Seminar',
    location: 'Daring',
    benefits: 'E-Sertifikast\nIlmu yang bermanfaat\nrelasi',
    requirements: 'Mahasiswa',
    timeStart: DateTime.utc(
      2021,
      5,
      1,
      8,
    ),
    timeReglimit: DateTime.utc(
      2021,
      4,
      29,
      0,
    ),
    status: 'Publish',
    organizer: 'HIMATIF',
    contactOrganizer: '089713199',
  ),
  EventInfo(
    id: 5,
    idUser: 1,
    name: 'Seminar Nasional 4',
    cost: 'Gratiss',
    posterEvent:
        'https://eventkampus.com/data/event/poster/2/seminar-administrasi-bisnis-pnj_1.jpeg',
    description: 'Seminar Inovasi SDM dan Iptek Nuklir',
    category: 'Seminar',
    location: 'Daring',
    benefits: 'E-Sertifikast\nIlmu yang bermanfaat\nrelasi',
    requirements: 'Mahasiswa',
    timeStart: DateTime.utc(
      2021,
      5,
      1,
      8,
    ),
    timeReglimit: DateTime.utc(
      2021,
      4,
      29,
      0,
    ),
    status: 'Pending',
    organizer: 'HIMATIF',
    contactOrganizer: '089713199',
  ),
  EventInfo(
    id: 6,
    idUser: 1,
    name: 'Seminar Nasional 5',
    cost: 'Gratiss',
    posterEvent:
        'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/business-design-template-7916298b6ab556c65ba52d907da3ca8c.jpg?ts=1583694697',
    description: 'Seminar Inovasi SDM dan Iptek Nuklir',
    category: 'Seminar',
    location: 'Daring',
    benefits: 'E-Sertifikast\nIlmu yang bermanfaat\nrelasi',
    requirements: 'Mahasiswa',
    timeStart: DateTime.utc(
      2021,
      5,
      1,
      8,
    ),
    timeReglimit: DateTime.utc(
      2021,
      4,
      29,
      0,
    ),
    status: 'Publish',
    organizer: 'HIMATIF',
    contactOrganizer: '089713199',
  ),
];
